name: Anydataset-db(1.3)
title: Anydataset-db(2)

project:
  version: 4.0.0
  download_url: https://github.com/byjg/anydata-set/releases

license:
  software: MIT
  software_url: https://opensource.org/licenses/MIT
  
  docs: MIT
  docs_url: https://opensource.org/licenses/MIT
  
git_edit_address: https://github.com/byjg/anydataset-db/tree/master/

links:
  header:
    - title: GitHub
      url: https://github.com/byjg/anydataset-db
    - title: More
      url: https://opensource.byjg.com/
  footer:
    - title: GitHub
      url: https://github.com/byjg/anydataset-db
    - title: Issues
      url: https://github.com/byjg/anydataset-db/issues

ui:
  header:
    color1: "#080331"
    color2: "#673051"
    trianglify: true

social:
    github:
        user: byjg
        repo: anydataset-db
    twitter:
        enabled: false
        via:
        hash:
        account:
    facebook:
        enabled: false
        profileUrl:

analytics:
    google: UA-123456-1

# Build settings
markdown: kramdown
remote_theme: allejo/jekyll-docs-theme
