name: Anydataset-db
title: Anydataset-db

project:
  version: 4.0.0
  download_url: https://github.com/byjg/anydata-set/releases

license:
  software: MIT
  software_url: https://opensource.org/licenses/MIT

git_edit_address: https://github.com/byjg/anydataset-db/tree/master/

links:
  header:
    - title: GitHub
      url: https://github.com/byjg/anydataset-db
  footer:
    - title: GitHub
      url: https://github.com/byjg/anydataset-db
    - title: Issues
      url: https://github.com/byjg/anydataset-db/issues

ui:
  header:
    color1: "#080331"
    color2: "#673051"
    trianglify: true

social:
  github:
    user: byjg
    repo: anydataset-db

disqus: false

description: >-
  Lorem Ipsum
  
remote_theme: allejo/jekyll-docs-theme

